# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_src/client.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563, 452)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chat = QtWidgets.QTextEdit(self.centralwidget)
        self.chat.setGeometry(QtCore.QRect(23, 29, 511, 331))
        self.chat.setReadOnly(True)
        self.chat.setObjectName("chat")
        self.enter = QtWidgets.QTextEdit(self.centralwidget)
        self.enter.setGeometry(QtCore.QRect(20, 390, 401, 41))
        self.enter.setObjectName("enter")
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setGeometry(QtCore.QRect(440, 390, 91, 41))
        self.send.setObjectName("send")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.send.setText(_translate("MainWindow", "Отправить"))
        self.send.setShortcut(_translate("MainWindow", "Ctrl+Return"))
